sudo: false

language: generic

os:
  - osx

python:
 - "3.5"

addons:
  apt:
    packages:
    - git

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

install:
  - if [ "$(git ls-remote --heads https://github.com/gem/oq-hazardlib.git ${TRAVIS_BRANCH})" != "" ]; then BRANCH=$TRAVIS_BRANCH; else BRANCH='master'; fi; git clone -b ${BRANCH} --depth=1 https://github.com/gem/oq-hazardlib.git && echo "Running on oq-hazardlib/${BRANCH}"
  - pip install -e oq-hazardlib/
  - pip install -e .

script:
  - nosetests --with-doctest -vsx -a'!slow'
  - cat /tmp/webui*
  - bin/oq info -r demos/hazard
  - bin/oq reset --yes

after_success:
  - pip install sphinx==1.3.6
  - cd doc/sphinx
  - make html
